# Import Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

# Import Data

In [6]:
dataset = pd.read_csv('ds.csv')
dataset.head()
#Keterangan = 0 = Perpanjang
#Keterangan = 1 = Tidak Diperpanjang

Nama  Kehadiran  Kedisiplinan  Tanggung Jawab  Attitude  Komunikasi  \
0   Agung          5             5               4         5           5   
1    Agus          5             5               5         5           4   
2    Asep          4             5               4         4           5   
3  Andika          4             5               5         4           4   
4  Andika          3             5               5         3           3   

   Jumlah  Keterangan  
0      24           0  
1      24           0  
2      22           0  
3      22           0  
4      19           1

In [4]:
dataset

Nama  Kehadiran  Kedisiplinan  Tanggung Jawab  Attitude  Komunikasi  \
0       Agung          5             5               4         5           5   
1        Agus          5             5               5         5           4   
2        Asep          4             5               4         4           5   
3      Andika          4             5               5         4           4   
4      Andika          3             5               5         3           3   
..        ...        ...           ...             ...       ...         ...   
636      Zeke          5             4               3         4           5   
637  Zeppelin          4             5               3         4           3   
638    Zidane          4             5               5         4           5   
639      Ziva          4             5               4         4           5   
640   Zulfian          4             5               5         4           5   

     Jumlah  Keterangan  
0        24           0  
1        24           0  
2        22           0  
3        22           0  
4        19           1  
..      ...         ...  
636      21           0  
637      19           1  
638      23           0  
639      22           0  
640      23           0  

[641 rows x 8 columns]

In [10]:
x = dataset.iloc [:, :7].values
y = dataset.iloc [:, 7].values

In [11]:
print(x)

[['Agung' 5 5 ... 5 5 24]
 ['Agus' 5 5 ... 5 4 24]
 ['Asep' 4 5 ... 4 5 22]
 ...
 ['Zidane' 4 5 ... 4 5 23]
 ['Ziva' 4 5 ... 4 5 22]
 ['Zulfian' 4 5 ... 4 5 23]]


In [12]:
print(y)

[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1
 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1
 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 1 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 0
 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 0] = le.fit_transform(x[:, 0])

In [14]:
print(x)

[[8 5 5 ... 5 5 24]
 [9 5 5 ... 5 4 24]
 [31 4 5 ... 4 5 22]
 ...
 [490 4 5 ... 4 5 23]
 [491 4 5 ... 4 5 22]
 [492 4 5 ... 4 5 23]]


# Split Data

In [16]:
from sklearn.model_selection import train_test_split

In [37]:
x_train, x_test, y_train, y_test = train_test_split (x,y, test_size = 5, random_state = 0)

In [38]:
print(x_test)

[[100 5 4 5 4 4 22]
 [132 4 5 5 4 5 23]
 [444 5 3 3 5 3 19]
 [85 3 5 5 3 5 21]
 [445 4 5 4 4 5 22]]


# Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [41]:
print(x_train)

[[-0.60366287  0.8524885   0.89117156 ...  0.80304593  0.83325416
   1.60493992]
 [-0.54353818  0.8524885  -0.31990774 ...  0.80304593 -0.44066326
   0.15433577]
 [ 1.07982862 -0.4699083   0.89117156 ... -0.62359432  0.83325416
  -0.32919895]
 ...
 [-0.61702392  0.8524885   0.89117156 ...  0.80304593  0.83325416
   0.63787049]
 [ 1.36709106  0.8524885  -1.53098704 ... -0.62359432 -0.44066326
  -1.29626839]
 [ 0.89945453  0.8524885  -1.53098704 ...  0.80304593 -1.71458067
  -0.32919895]]


# Training

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

# Predict 

In [44]:
y_pred = classifier.predict(x_test)

In [45]:
print(y_pred)

[0 0 1 0 0]


In [46]:
print(y_test)

[0 0 1 0 0]


# Evaluasi

In [48]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [49]:
cs = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [50]:
cs

array([[4, 0],
       [0, 1]], dtype=int64)

In [51]:
ac

1.0